language: python

matrix:
  include:
  - name: 3.8
    python:  "3.8"
    dist: xenial
    sudo: true
  - name: 3.7
    python:  "3.7"
    dist: xenial
    sudo: true
  - name: 3.6
    python: "3.6"
  - name: 3.5
    python: "3.5"
  - name: 3.4
    python: "3.4"
  - name: 2.7
    python: "2.7"
  - name: pypy
    python: "pypy"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install enchant

install:
  - pip install -r requirements.txt
  - pip install coveralls

script: python setup.py test

after_success:
  coveralls
